#!/bin/bash

#!/bin/bash
echo "Reach Entry Point"
echo $$ > ~/user_enrypoint.pid

set -e

loop=0

run_bash=0

echo 'akrruser' | sudo -S ls

start_process(){
    name=$1
    command=$2
    pid_file=$3

    if [ ! -f "${pid_file}" ]; then
        echo "Launching ${name}"
        ${command}
    elif [ ! -f "/proc/`cat ${pid_file}`" ]; then
        echo "Launching ${name}"
        ${command}
    else
        echo "${name} already running"
    fi
}

# Start process and confirm it launches by looking for a
# confirm_sentence in log_file.
# Format:
# start_process_w_confirm name command pid_file log_file confirm_sentence
start_process_w_confirm(){
    name=$1
    command=$2
    pid_file=$3
    log_file=$4
    confirm_sentence=$5
    timeout_time=2

    if [ -f "${pid_file}" ]; then
        if [  -d "/proc/`cat ${pid_file}`" ]; then
            echo "${name} already running"
            return 1
        fi
    fi

    if [ -f "${log_file}" ]; then
        cat "${log_file}" >> "${log_file}.old"
        rm "${log_file}"
    fi

    echo "Launching ${name}"
    ${command}

    for ((i=0; i < ${timeout_time}; i++))
    {
        if grep -q ${confirm_sentence} ${log_file} ; then
            echo "${name} is up"
            return 0
        fi
        sleep 1
    }

    echo "Something wrong with ${name}, can not find key-phrase in log"
    return 1
}


for var in "$@"
do
    case "$var" in
    mysqld)
        sudo /sbin/cmd_start mysqld
        ;;
    munged)
        sudo /sbin/cmd_start munged
        ;;
    sshd)
        sudo /sbin/cmd_start sshd
        ;;
    slurmdbd)
        sudo /sbin/cmd_start slurmdbd
        ;;
    slurmctld)
        sudo /sbin/cmd_start slurmctld
        ;;
    slurmd)
        sudo /sbin/cmd_start slurmd
        ;;
    httpd)
        echo "Launching httpd"
        httpd
        ;;
    self_contained_slurm_wlm)
        sudo /sbin/cmd_start munged sshd mysqld slurmdbd slurmctld slurmd
        ;;
    bash)
        echo "Launching bash"
        run_bash=1
        ;;
    -loop)
        loop=1
        ;;
    -set-no-exit-on-fail)
        set +e
        ;;
    -set-exit-on-fail)
        set -e
        ;;
    *)
        echo "Executing ${var}"
        ${var}
        ;;
    esac
done

if [ $run_bash -eq 1 ]; then
    /bin/bash
elif [ $loop -eq 1 ]; then
    echo "All requested daemon launched"
    while true; do
        sleep 60
    done
fi
