# Run regtest1 in docker
FROM nsimakov/akrr_ready_centos_slurm_single_host_wlm:latest

LABEL description="image to run tests with git repo location like in shippable"

ENV REPO_FULL_NAME=ubccr/akrr

ENTRYPOINT ["/usr/local/sbin/cmd_start"]
CMD ["-set-no-exit-on-fail", \
     "chown -R akrruser:akrruser /home/akrruser/akrr_src", \
     "su akrruser -c 'bash /home/akrruser/akrr_src/tests/regtest1/run_test_on_shippable.sh'", \
     "bash_akrruser"]
