#!/bin/bash


#Common commands
export AKRR_NODES=1
export AKRR_CORES=8
export AKRR_CORES_PER_NODE=8
export AKRR_NETWORK_SCRATCH="/home/nikolays/xdmod_wsp/akrr_scratch"
export AKRR_LOCAL_SCRATCH="/tmp"
export AKRR_TASK_WORKDIR="/home/nikolays/xdmod_wsp/akrr_scratch/akrr_data/bumblebee/openfoam/2022.12.04.16.23.02.337401"
export AKRR_APPKER_DIR="/home/nikolays/xdmod_wsp/akrr_scratch/appker"
export AKRR_AKRR_DIR="/home/nikolays/xdmod_wsp/akrr_scratch/akrr_data/bumblebee"

export AKRR_APPKER_NAME="openfoam"
export AKRR_RESOURCE_NAME="bumblebee"
export AKRR_TIMESTAMP="2022.12.04.16.23.02.337401"
export AKRR_APP_STDOUT_FILE="$AKRR_TASK_WORKDIR/appstdout"

export AKRR_APPKERNEL_INPUT="/home/nikolays/xdmod_wsp/akrr_scratch/appker/inputs/openfoam/motorBike"
export AKRR_APPKERNEL_EXECUTABLE="/home/nikolays/xdmod_wsp/akrr_scratch/appker/execs"

source "$AKRR_APPKER_DIR/execs/bin/akrr_util.bash"

#Populate list of nodes per MPI process
export AKRR_NODELIST=`printf 'localhost %.0s' $(seq 1 ${AKRR_CORES})|xargs`

export PATH="$AKRR_APPKER_DIR/execs/bin:$PATH"

cd "$AKRR_TASK_WORKDIR"

#run common tests
akrr_perform_common_tests

#Write some info to gen.info, JSON-Like file
akrr_write_to_gen_info "start_time" "`date`"
akrr_write_to_gen_info "node_list" "$AKRR_NODELIST"
akrr_write_to_gen_info "input_param" "inputs/openfoam/motorBike"


#create working dir
export AKRR_TMP_WORKDIR=`mktemp -d /home/nikolays/xdmod_wsp/akrr_scratch/ak.XXXXXXXXX`
echo "Temporary working directory: $AKRR_TMP_WORKDIR"
cd $AKRR_TMP_WORKDIR

#Copy inputs
if [ -d "/home/nikolays/xdmod_wsp/akrr_scratch/appker/inputs/openfoam/motorBike" ]
then
    cp -r /home/nikolays/xdmod_wsp/akrr_scratch/appker/inputs/openfoam/motorBike/* ./
fi
if [ -f "/home/nikolays/xdmod_wsp/akrr_scratch/appker/inputs/openfoam/motorBike" ]
then
    cp /home/nikolays/xdmod_wsp/akrr_scratch/appker/inputs/openfoam/motorBike ./
fi



# Load application environment
source ~/spack/share/spack/setup-env.sh
spack load openfoam

# openfoam executable for appsig calculation
EXE=`which simpleFoam`

# set how to run app kernel
RUN_APPKERNEL="./AllrunAKRR"


# Generate AppKer signature
appsigcheck.sh $EXE $AKRR_TASK_WORKDIR/.. >> $AKRR_APP_STDOUT_FILE


#Execute AppKer
akrr_write_to_gen_info "appkernel_start_time" "`date`"
$RUN_APPKERNEL >> $AKRR_APP_STDOUT_FILE 2>&1
akrr_write_to_gen_info "appkernel_end_time" "`date`"




#clean-up
cd $AKRR_TASK_WORKDIR
if [ "${AKRR_DEBUG=no}" = "no" ]
then
    echo "Deleting temporary files"
    rm -rf $AKRR_TMP_WORKDIR
else
    echo "Copying temporary files"
    cp -r $AKRR_TMP_WORKDIR workdir
    rm -rf $AKRR_TMP_WORKDIR
fi



akrr_write_to_gen_info "end_time" "`date`"
