#!/bin/bash
#SBATCH -J graph500
#SBATCH -e /scratch/01482/xdtas/akrrdata/stampede2-knl/graph500/2021.08.11.10.49.16.139021/stderr
#SBATCH -o /scratch/01482/xdtas/akrrdata/stampede2-knl/graph500/2021.08.11.10.49.16.139021/stdout
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=64
#SBATCH -p normal
#SBATCH -t 00:09:00
#SBATCH -A TG-CCR120014
#SBATCH --mail-user=xdtas@ccr.buffalo.edu



#Common commands
export AKRR_NODES=2
export AKRR_CORES=128
export AKRR_CORES_PER_NODE=64
export AKRR_NETWORK_SCRATCH="/scratch/01482/xdtas"
export AKRR_LOCAL_SCRATCH="/tmp"
export AKRR_TASK_WORKDIR="/scratch/01482/xdtas/akrrdata/stampede2-knl/graph500/2021.08.11.10.49.16.139021"
export AKRR_APPKER_DIR="/work/01482/xdtas/appker/stampede2-knl"
export AKRR_AKRR_DIR="/scratch/01482/xdtas/akrrdata/stampede2-knl"

export AKRR_APPKER_NAME="graph500"
export AKRR_RESOURCE_NAME="stampede2-knl"
export AKRR_TIMESTAMP="2021.08.11.10.49.16.139021"
export AKRR_APP_STDOUT_FILE="$AKRR_TASK_WORKDIR/appstdout"

export AKRR_APPKERNEL_INPUT="/work/01482/xdtas/appker/stampede2-knl/inputs"
export AKRR_APPKERNEL_EXECUTABLE="/work/01482/xdtas/appker/stampede2-knl/execs/graph500/src/graph500_reference_bfs_sssp"

source "$AKRR_APPKER_DIR/execs/bin/akrr_util.bash"

#Populate list of nodes per MPI process
export AKRR_NODELIST=`srun -l hostname -s|sort -n| awk '{printf "%s ",$2}' `

export PATH="$AKRR_APPKER_DIR/execs/bin:$PATH"

cd "$AKRR_TASK_WORKDIR"

#run common tests
akrr_perform_common_tests

#Write some info to gen.info, JSON-Like file
akrr_write_to_gen_info "start_time" "`date`"
akrr_write_to_gen_info "node_list" "$AKRR_NODELIST"



#create working dir
export AKRR_TMP_WORKDIR=`mktemp -d /scratch/01482/xdtas/ior.XXXXXXXXX`
echo "Temporary working directory: $AKRR_TMP_WORKDIR"
cd $AKRR_TMP_WORKDIR

#set executable location
EXE=/work/01482/xdtas/appker/stampede2-knl/execs/graph500/src/graph500_reference_bfs_sssp




#Load application environment
module list


#set how to run app kernel
#only run one process per node
RUN_APPKERNEL="ibrun /work/01482/xdtas/appker/stampede2-knl/execs/graph500/src/graph500_reference_bfs_sssp 23 16"


# Generate AppKer signature
appsigcheck.sh $EXE $AKRR_TASK_WORKDIR/.. >> $AKRR_APP_STDOUT_FILE


#Execute AppKer
akrr_write_to_gen_info "appkernel_start_time" "`date`"
$RUN_APPKERNEL >> $AKRR_APP_STDOUT_FILE 2>&1
akrr_write_to_gen_info "appkernel_end_time" "`date`"




#clean-up
cd $AKRR_TASK_WORKDIR
if [ "${AKRR_DEBUG=no}" = "no" ]
then
        echo "Deleting temporary files"
        rm -rf $AKRR_TMP_WORKDIR
else
        echo "Copying temporary files"
        cp -r $AKRR_TMP_WORKDIR workdir
        rm -rf $AKRR_TMP_WORKDIR
fi



akrr_write_to_gen_info "end_time" "`date`"
